import type { Metadata } from 'next';
import { Navbar } from '@/components/landing/navbar';
import { Footer } from '@/components/landing/footer';
import { siteConfig } from '@/lib/site';

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: `Terms of service for using ${siteConfig.name}.`,
  alternates: { canonical: '/terms' },
};

const sections = [
  {
    title: 'Acceptance of terms',
    body: `By accessing or using ${siteConfig.name}, you agree to be bound by these terms. If you do not agree, please do not use the service.`,
  },
  {
    title: 'Use of the service',
    body: `${siteConfig.name} provides AI-generated technology recommendations for informational purposes. The service is provided as-is and is intended to help you evaluate technology options.`,
  },
  {
    title: 'No warranty',
    body: 'Recommendations are generated by AI and may contain errors or omissions. They do not constitute professional, financial, or legal advice. You are responsible for evaluating and verifying any technology you choose to adopt.',
  },
  {
    title: 'Acceptable use',
    body: 'You agree not to misuse the service, including attempting to disrupt it, reverse-engineer the analysis, or use it for unlawful purposes.',
  },
  {
    title: 'Intellectual property',
    body: 'The Turf DRS name, branding, and site content belong to Turf DRS. You may reference Turf DRS and link to it, but you may not copy or reuse the site or its content for commercial purposes without permission.',
  },
  {
    title: 'Limitation of liability',
    body: 'To the maximum extent permitted by law, Turf DRS is not liable for any direct, indirect, incidental, or consequential damages arising from your use of the service.',
  },
  {
    title: 'Changes to these terms',
    body: 'We may update these terms from time to time. Continued use of the service after changes constitutes acceptance of the revised terms.',
  },
];

export default function TermsPage() {
  return (
    <main className="relative min-h-screen overflow-x-hidden">
      <Navbar />
      <div className="relative overflow-hidden px-4 pb-24 pt-32 sm:px-6 sm:pt-36">
        <div className="pointer-events-none absolute left-1/2 top-0 -z-10 h-[400px] w-[700px] -translate-x-1/2 rounded-full bg-teal-500/10 blur-[120px]" />

        <header className="mx-auto max-w-3xl text-center">
          <p className="text-sm font-medium text-teal-400">Legal</p>
          <h1 className="mt-3 text-balance text-3xl font-semibold tracking-tight text-foreground sm:text-5xl">
            Terms of <span className="gradient-text">Service</span>
          </h1>
          <p className="mx-auto mt-4 max-w-xl text-base leading-relaxed text-muted-foreground sm:text-lg">
            Last updated: August 2026
          </p>
        </header>

        <div className="mx-auto mt-14 max-w-2xl space-y-10">
          {sections.map((section) => (
            <section key={section.title}>
              <h2 className="text-lg font-semibold text-foreground">{section.title}</h2>
              <p className="mt-2 text-[15px] leading-relaxed text-muted-foreground">{section.body}</p>
            </section>
          ))}
        </div>
      </div>
      <Footer />
    </main>
  );
}
